id: 6a830e3f243143eeb8306106376aff4e
initial_creation_type: ocr
source_metadata:
  volumes:
    ae176017a4ad47388bc780202de5979d:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ''
      total_pages: 1539
      volume_number: 1
